import { ThemeDefinition, ThemeId } from '../types/theme';

export const THEME_DEFINITIONS: Record<ThemeId, ThemeDefinition> = {
  indigo: {
    id: 'indigo',
    name: 'Dark Earth',
    subtitle: 'Warm Charcoal & Earthy Brown',
    tag: 'Recommended',
    primaryColor: '#49362F',
    primaryHover: '#3A2B25',
    primaryLight: 'rgba(73, 54, 47, 0.12)',
    secondaryColor: '#A56F5D',
    chartColor: '#49362F',
    darkPrimaryColor: '#6A5045',
    darkPrimaryHover: '#7D5F52',
    darkPrimaryLight: 'rgba(213, 189, 167, 0.15)',
    darkTextColor: '#D5BDA7',
    darkChartColor: '#D5BDA7',
    darkSecondaryColor: '#C48C7B',
    logoGradient: 'from-[#49362F] to-[#292522]',
    glowColor: 'shadow-xs',
    swatchBg: 'bg-[#49362F]',
    description: 'Calm earthy palette with dark earth charcoal, warm beige, and terracotta accents.',
  },
  sapphire: {
    id: 'sapphire',
    name: 'Warm Terracotta',
    subtitle: 'Rich Clay & Sunbaked Rust',
    tag: 'Earthy',
    primaryColor: '#C25E3E',
    primaryHover: '#A74A2C',
    primaryLight: 'rgba(194, 94, 62, 0.14)',
    secondaryColor: '#E07A5F',
    chartColor: '#C25E3E',
    darkPrimaryColor: '#C25E3E',
    darkPrimaryHover: '#D46B4A',
    darkPrimaryLight: 'rgba(224, 122, 95, 0.18)',
    darkTextColor: '#E07A5F',
    darkChartColor: '#E07A5F',
    darkSecondaryColor: '#D5BDA7',
    logoGradient: 'from-[#C25E3E] to-[#8C3B24]',
    glowColor: 'shadow-xs',
    swatchBg: 'bg-[#C25E3E]',
    description: 'Rich terracotta clay paired with clean cream surfaces and warm terracotta accents.',
  },
  slate: {
    id: 'slate',
    name: 'Deep Slate',
    subtitle: 'Graphite Obsidian & Steel',
    tag: 'Minimal',
    primaryColor: '#1E293B',
    primaryHover: '#0F172A',
    primaryLight: 'rgba(30, 41, 59, 0.12)',
    secondaryColor: '#475569',
    chartColor: '#1E293B',
    darkPrimaryColor: '#475569',
    darkPrimaryHover: '#64748B',
    darkPrimaryLight: 'rgba(148, 163, 184, 0.16)',
    darkTextColor: '#94A3B8',
    darkChartColor: '#94A3B8',
    darkSecondaryColor: '#64748B',
    logoGradient: 'from-[#1E293B] to-[#334155]',
    glowColor: 'shadow-xs',
    swatchBg: 'bg-[#1E293B]',
    description: 'Crisp monochrome deep graphite slate with balanced contrast and titanium tones.',
  },
  emerald: {
    id: 'emerald',
    name: 'Muted Sage',
    subtitle: 'Deep Botanical Olive & Forest',
    tag: 'Operations',
    primaryColor: '#2E6F40',
    primaryHover: '#235732',
    primaryLight: 'rgba(46, 111, 64, 0.14)',
    secondaryColor: '#52B788',
    chartColor: '#2E6F40',
    darkPrimaryColor: '#2E6F40',
    darkPrimaryHover: '#3B8750',
    darkPrimaryLight: 'rgba(82, 183, 136, 0.16)',
    darkTextColor: '#52B788',
    darkChartColor: '#52B788',
    darkSecondaryColor: '#96A588',
    logoGradient: 'from-[#2E6F40] to-[#1B4332]',
    glowColor: 'shadow-xs',
    swatchBg: 'bg-[#2E6F40]',
    description: 'Subtle sage and forest botanical green on calm canvas with restrained organic accents.',
  },
  amber: {
    id: 'amber',
    name: 'Warm Umber',
    subtitle: 'Burnished Bronze & Amber',
    tag: 'Executive',
    primaryColor: '#B45309',
    primaryHover: '#92400E',
    primaryLight: 'rgba(180, 83, 9, 0.14)',
    secondaryColor: '#D97706',
    chartColor: '#B45309',
    darkPrimaryColor: '#B45309',
    darkPrimaryHover: '#D97706',
    darkPrimaryLight: 'rgba(217, 119, 6, 0.18)',
    darkTextColor: '#E59524',
    darkChartColor: '#D97706',
    darkSecondaryColor: '#D5BDA7',
    logoGradient: 'from-[#B45309] to-[#78350F]',
    glowColor: 'shadow-xs',
    swatchBg: 'bg-[#B45309]',
    description: 'Warm burnished bronze leather and sand surfaces with radiant executive gold styling.',
  },
  violet: {
    id: 'violet',
    name: 'Muted Plum',
    subtitle: 'Royal Mulberry & Amethyst',
    tag: 'Analytics',
    primaryColor: '#7E3B68',
    primaryHover: '#632B51',
    primaryLight: 'rgba(126, 59, 104, 0.14)',
    secondaryColor: '#A8518A',
    chartColor: '#7E3B68',
    darkPrimaryColor: '#7E3B68',
    darkPrimaryHover: '#94487B',
    darkPrimaryLight: 'rgba(168, 81, 138, 0.18)',
    darkTextColor: '#C97BB0',
    darkChartColor: '#C97BB0',
    darkSecondaryColor: '#D5BDA7',
    logoGradient: 'from-[#7E3B68] to-[#4A1D3C]',
    glowColor: 'shadow-xs',
    swatchBg: 'bg-[#7E3B68]',
    description: 'Restrained earthy royal mulberry plum tone paired with warm cream and amethyst.',
  },
};

export const THEME_LIST = Object.values(THEME_DEFINITIONS);
